### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64 On Mac 

### ISSUE THREAD

**Issue by knkrth** [NeblioTeam/neblio#22]
Hi, I got ld: symbol(s) not found for architecture x86_64 error while building on Mac. Can you provide me What Mac OS you use & boost version.

**Comment by NeblioTeam** [comment]
For the mac binary I build with 10.12.6 using QT-Creator
boost ver 1.64
