### ISSUE TITLE
Build failed on Ubuntu 

### ISSUE THREAD

**Issue by blockinator** [NeblioTeam/neblio#271]
I am trying to build the QT wallet on Ubuntu 18.04 and I get this error:
```
/usr/bin/ld: cannot find -lqrencode
collect2: error: ld returned 1 exit status
```

**Comment by NeblioTeam** [comment]
Did you follow the instructions here exactly? https://github.com/NeblioTeam/neblio#building-neblio they were just recently updated and verified to be working on 18.04

If you still have trouble, comment back with each command you ran, and the full output and we'll re-open this issue and see if we can help.

**Comment by blockinator** [comment]
Whoops I forget to export the qrencode. I did that and now I get this error:
```
../qt/overviewpage.cpp:88:10: fatal error: overviewpage.moc: No such file or directory
 #include "overviewpage.moc"
compilation terminated.
Makefile:6537: recipe for target 'build/overviewpage.o' failed
```

**Comment by NeblioTeam** [comment]
> If you still have trouble, comment back with each command you ran, and the full output and we'll re-open this issue and see if we can help.

It looks like you are in the wrong directory, but without the above requested info it is impossible to tell.
